version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: production_db
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    volumes:
      - ./node_modules:/app/node_modules
    container_name: nestjs-app
    ports:
      - '3000:3000'
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: production_db
    depends_on:
      - mysql

volumes:
  mysql-data:
